/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileRegion } from './FileRegion';
import {
    FileRegionFromJSON,
    FileRegionFromJSONTyped,
    FileRegionToJSON,
    FileRegionToJSONTyped,
} from './FileRegion';

/**
 * Alternative location to download file from
 * @export
 * @interface ExternalResource
 */
export interface ExternalResource {
    /**
     * 
     * @type {Array<FileRegion>}
     * @memberof ExternalResource
     */
    fileRegions: Array<FileRegion>;
}

/**
 * Check if a given object implements the ExternalResource interface.
 */
export function instanceOfExternalResource(value: object): value is ExternalResource {
    if (!('fileRegions' in value) || value['fileRegions'] === undefined) return false;
    return true;
}

export function ExternalResourceFromJSON(json: any): ExternalResource {
    return ExternalResourceFromJSONTyped(json, false);
}

export function ExternalResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalResource {
    if (json == null) {
        return json;
    }
    return {
        
        'fileRegions': ((json['fileRegions'] as Array<any>).map(FileRegionFromJSON)),
    };
}

export function ExternalResourceToJSON(json: any): ExternalResource {
    return ExternalResourceToJSONTyped(json, false);
}

export function ExternalResourceToJSONTyped(value?: ExternalResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileRegions': ((value['fileRegions'] as Array<any>).map(FileRegionToJSON)),
    };
}

