/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata for a message in the Fidd file system
 * @export
 * @interface FiddFileMetadata
 */
export interface FiddFileMetadata {
    /**
     * 
     * @type {number}
     * @memberof FiddFileMetadata
     */
    messageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof FiddFileMetadata
     */
    originalMessageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof FiddFileMetadata
     */
    previousMessageNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof FiddFileMetadata
     */
    postId: string;
    /**
     * 
     * @type {number}
     * @memberof FiddFileMetadata
     */
    versionNumber: number;
    /**
     * 
     * @type {boolean}
     * @memberof FiddFileMetadata
     */
    isNewOrSquash: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FiddFileMetadata
     */
    isDelete: boolean;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof FiddFileMetadata
     */
    originalMessageCreationTime?: number;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof FiddFileMetadata
     */
    messageCreationTime?: number;
    /**
     * 
     * @type {string}
     * @memberof FiddFileMetadata
     */
    authorsPublicKeyFormat?: string;
    /**
     * Base64-encoded public key
     * @type {string}
     * @memberof FiddFileMetadata
     */
    authorsPublicKey?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FiddFileMetadata
     */
    authorsFiddFileSignatureFormats?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FiddFileMetadata
     */
    authorsFiddKeyFileSignatureFormats?: Array<string>;
}

/**
 * Check if a given object implements the FiddFileMetadata interface.
 */
export function instanceOfFiddFileMetadata(value: object): value is FiddFileMetadata {
    if (!('messageNumber' in value) || value['messageNumber'] === undefined) return false;
    if (!('originalMessageNumber' in value) || value['originalMessageNumber'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('versionNumber' in value) || value['versionNumber'] === undefined) return false;
    if (!('isNewOrSquash' in value) || value['isNewOrSquash'] === undefined) return false;
    if (!('isDelete' in value) || value['isDelete'] === undefined) return false;
    return true;
}

export function FiddFileMetadataFromJSON(json: any): FiddFileMetadata {
    return FiddFileMetadataFromJSONTyped(json, false);
}

export function FiddFileMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiddFileMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'messageNumber': json['messageNumber'],
        'originalMessageNumber': json['originalMessageNumber'],
        'previousMessageNumber': json['previousMessageNumber'] == null ? undefined : json['previousMessageNumber'],
        'postId': json['postId'],
        'versionNumber': json['versionNumber'],
        'isNewOrSquash': json['isNewOrSquash'],
        'isDelete': json['isDelete'],
        'originalMessageCreationTime': json['originalMessageCreationTime'] == null ? undefined : json['originalMessageCreationTime'],
        'messageCreationTime': json['messageCreationTime'] == null ? undefined : json['messageCreationTime'],
        'authorsPublicKeyFormat': json['authorsPublicKeyFormat'] == null ? undefined : json['authorsPublicKeyFormat'],
        'authorsPublicKey': json['authorsPublicKey'] == null ? undefined : json['authorsPublicKey'],
        'authorsFiddFileSignatureFormats': json['authorsFiddFileSignatureFormats'] == null ? undefined : json['authorsFiddFileSignatureFormats'],
        'authorsFiddKeyFileSignatureFormats': json['authorsFiddKeyFileSignatureFormats'] == null ? undefined : json['authorsFiddKeyFileSignatureFormats'],
    };
}

export function FiddFileMetadataToJSON(json: any): FiddFileMetadata {
    return FiddFileMetadataToJSONTyped(json, false);
}

export function FiddFileMetadataToJSONTyped(value?: FiddFileMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageNumber': value['messageNumber'],
        'originalMessageNumber': value['originalMessageNumber'],
        'previousMessageNumber': value['previousMessageNumber'],
        'postId': value['postId'],
        'versionNumber': value['versionNumber'],
        'isNewOrSquash': value['isNewOrSquash'],
        'isDelete': value['isDelete'],
        'originalMessageCreationTime': value['originalMessageCreationTime'],
        'messageCreationTime': value['messageCreationTime'],
        'authorsPublicKeyFormat': value['authorsPublicKeyFormat'],
        'authorsPublicKey': value['authorsPublicKey'],
        'authorsFiddFileSignatureFormats': value['authorsFiddFileSignatureFormats'],
        'authorsFiddKeyFileSignatureFormats': value['authorsFiddKeyFileSignatureFormats'],
    };
}

