/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A signature or checksum
 * @export
 * @interface FiddSignature
 */
export interface FiddSignature {
    /**
     * 
     * @type {string}
     * @memberof FiddSignature
     */
    format: string;
    /**
     * Base64-encoded signature/checksum bytes
     * @type {string}
     * @memberof FiddSignature
     */
    bytes: string;
}

/**
 * Check if a given object implements the FiddSignature interface.
 */
export function instanceOfFiddSignature(value: object): value is FiddSignature {
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    return true;
}

export function FiddSignatureFromJSON(json: any): FiddSignature {
    return FiddSignatureFromJSONTyped(json, false);
}

export function FiddSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiddSignature {
    if (json == null) {
        return json;
    }
    return {
        
        'format': json['format'],
        'bytes': json['bytes'],
    };
}

export function FiddSignatureToJSON(json: any): FiddSignature {
    return FiddSignatureToJSONTyped(json, false);
}

export function FiddSignatureToJSONTyped(value?: FiddSignature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': value['format'],
        'bytes': value['bytes'],
    };
}

