/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FiddSignature } from './FiddSignature';
import {
    FiddSignatureFromJSON,
    FiddSignatureFromJSONTyped,
    FiddSignatureToJSON,
    FiddSignatureToJSONTyped,
} from './FiddSignature';

/**
 * Section information from FiddKey
 * @export
 * @interface FiddKeySection
 */
export interface FiddKeySection {
    /**
     * 
     * @type {number}
     * @memberof FiddKeySection
     */
    sectionOffset: number;
    /**
     * 
     * @type {number}
     * @memberof FiddKeySection
     */
    sectionLength: number;
    /**
     * 
     * @type {string}
     * @memberof FiddKeySection
     */
    encryptionAlgorithm?: string;
    /**
     * Base64-encoded encryption key data (algorithm-specific, may include key + IV)
     * @type {string}
     * @memberof FiddKeySection
     */
    encryptionKeyData?: string;
    /**
     * 
     * @type {Array<FiddSignature>}
     * @memberof FiddKeySection
     */
    crcs?: Array<FiddSignature>;
    /**
     * Size of header in section (v1.1)
     * @type {number}
     * @memberof FiddKeySection
     */
    headerLength?: number;
}

/**
 * Check if a given object implements the FiddKeySection interface.
 */
export function instanceOfFiddKeySection(value: object): value is FiddKeySection {
    if (!('sectionOffset' in value) || value['sectionOffset'] === undefined) return false;
    if (!('sectionLength' in value) || value['sectionLength'] === undefined) return false;
    return true;
}

export function FiddKeySectionFromJSON(json: any): FiddKeySection {
    return FiddKeySectionFromJSONTyped(json, false);
}

export function FiddKeySectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiddKeySection {
    if (json == null) {
        return json;
    }
    return {
        
        'sectionOffset': json['sectionOffset'],
        'sectionLength': json['sectionLength'],
        'encryptionAlgorithm': json['encryptionAlgorithm'] == null ? undefined : json['encryptionAlgorithm'],
        'encryptionKeyData': json['encryptionKeyData'] == null ? undefined : json['encryptionKeyData'],
        'crcs': json['crcs'] == null ? undefined : ((json['crcs'] as Array<any>).map(FiddSignatureFromJSON)),
        'headerLength': json['headerLength'] == null ? undefined : json['headerLength'],
    };
}

export function FiddKeySectionToJSON(json: any): FiddKeySection {
    return FiddKeySectionToJSONTyped(json, false);
}

export function FiddKeySectionToJSONTyped(value?: FiddKeySection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sectionOffset': value['sectionOffset'],
        'sectionLength': value['sectionLength'],
        'encryptionAlgorithm': value['encryptionAlgorithm'],
        'encryptionKeyData': value['encryptionKeyData'],
        'crcs': value['crcs'] == null ? undefined : ((value['crcs'] as Array<any>).map(FiddSignatureToJSON)),
        'headerLength': value['headerLength'],
    };
}

