/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Region of a file in an external resource
 * @export
 * @interface FileRegion
 */
export interface FileRegion {
    /**
     * 
     * @type {number}
     * @memberof FileRegion
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof FileRegion
     */
    length: number;
    /**
     * 
     * @type {string}
     * @memberof FileRegion
     */
    regionFileName: string;
    /**
     * Type of resource descriptor
     * @type {FileRegionResourceDescriptorTypeEnum}
     * @memberof FileRegion
     */
    resourceDescriptorType: FileRegionResourceDescriptorTypeEnum;
    /**
     * Base64-encoded resource descriptor
     * @type {string}
     * @memberof FileRegion
     */
    resourceDescriptor: string;
}


/**
 * @export
 */
export const FileRegionResourceDescriptorTypeEnum = {
    Url: 'URL'
} as const;
export type FileRegionResourceDescriptorTypeEnum = typeof FileRegionResourceDescriptorTypeEnum[keyof typeof FileRegionResourceDescriptorTypeEnum];


/**
 * Check if a given object implements the FileRegion interface.
 */
export function instanceOfFileRegion(value: object): value is FileRegion {
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('regionFileName' in value) || value['regionFileName'] === undefined) return false;
    if (!('resourceDescriptorType' in value) || value['resourceDescriptorType'] === undefined) return false;
    if (!('resourceDescriptor' in value) || value['resourceDescriptor'] === undefined) return false;
    return true;
}

export function FileRegionFromJSON(json: any): FileRegion {
    return FileRegionFromJSONTyped(json, false);
}

export function FileRegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileRegion {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'],
        'length': json['length'],
        'regionFileName': json['regionFileName'],
        'resourceDescriptorType': json['resourceDescriptorType'],
        'resourceDescriptor': json['resourceDescriptor'],
    };
}

export function FileRegionToJSON(json: any): FileRegion {
    return FileRegionToJSONTyped(json, false);
}

export function FileRegionToJSONTyped(value?: FileRegion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'length': value['length'],
        'regionFileName': value['regionFileName'],
        'resourceDescriptorType': value['resourceDescriptorType'],
        'resourceDescriptor': value['resourceDescriptor'],
    };
}

