/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FiddSignature } from './FiddSignature';
import {
    FiddSignatureFromJSON,
    FiddSignatureFromJSONTyped,
    FiddSignatureToJSON,
    FiddSignatureToJSONTyped,
} from './FiddSignature';
import type { ProgressiveCrc } from './ProgressiveCrc';
import {
    ProgressiveCrcFromJSON,
    ProgressiveCrcFromJSONTyped,
    ProgressiveCrcToJSON,
    ProgressiveCrcToJSONTyped,
} from './ProgressiveCrc';
import type { ExternalResource } from './ExternalResource';
import {
    ExternalResourceFromJSON,
    ExternalResourceFromJSONTyped,
    ExternalResourceToJSON,
    ExternalResourceToJSONTyped,
} from './ExternalResource';

/**
 * Metadata for a logical file
 * @export
 * @interface LogicalFileMetadata
 */
export interface LogicalFileMetadata {
    /**
     * Type of file update operation
     * @type {LogicalFileMetadataUpdateTypeEnum}
     * @memberof LogicalFileMetadata
     */
    updateType: LogicalFileMetadataUpdateTypeEnum;
    /**
     * Logical file path or name
     * @type {string}
     * @memberof LogicalFileMetadata
     */
    filePath: string;
    /**
     * Unix timestamp in milliseconds when the file was created
     * @type {number}
     * @memberof LogicalFileMetadata
     */
    createdAt?: number;
    /**
     * Unix timestamp in milliseconds when the file was last updated
     * @type {number}
     * @memberof LogicalFileMetadata
     */
    updatedAt?: number;
    /**
     * 
     * @type {Array<FiddSignature>}
     * @memberof LogicalFileMetadata
     */
    authorsFileSignatures?: Array<FiddSignature>;
    /**
     * 
     * @type {Array<ProgressiveCrc>}
     * @memberof LogicalFileMetadata
     */
    progressiveCrcs?: Array<ProgressiveCrc>;
    /**
     * 
     * @type {Array<ExternalResource>}
     * @memberof LogicalFileMetadata
     */
    externalLinks?: Array<ExternalResource>;
}


/**
 * @export
 */
export const LogicalFileMetadataUpdateTypeEnum = {
    CreateOverride: 'CREATE_OVERRIDE',
    Delete: 'DELETE'
} as const;
export type LogicalFileMetadataUpdateTypeEnum = typeof LogicalFileMetadataUpdateTypeEnum[keyof typeof LogicalFileMetadataUpdateTypeEnum];


/**
 * Check if a given object implements the LogicalFileMetadata interface.
 */
export function instanceOfLogicalFileMetadata(value: object): value is LogicalFileMetadata {
    if (!('updateType' in value) || value['updateType'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    return true;
}

export function LogicalFileMetadataFromJSON(json: any): LogicalFileMetadata {
    return LogicalFileMetadataFromJSONTyped(json, false);
}

export function LogicalFileMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogicalFileMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'updateType': json['updateType'],
        'filePath': json['filePath'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'authorsFileSignatures': json['authorsFileSignatures'] == null ? undefined : ((json['authorsFileSignatures'] as Array<any>).map(FiddSignatureFromJSON)),
        'progressiveCrcs': json['progressiveCrcs'] == null ? undefined : ((json['progressiveCrcs'] as Array<any>).map(ProgressiveCrcFromJSON)),
        'externalLinks': json['externalLinks'] == null ? undefined : ((json['externalLinks'] as Array<any>).map(ExternalResourceFromJSON)),
    };
}

export function LogicalFileMetadataToJSON(json: any): LogicalFileMetadata {
    return LogicalFileMetadataToJSONTyped(json, false);
}

export function LogicalFileMetadataToJSONTyped(value?: LogicalFileMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updateType': value['updateType'],
        'filePath': value['filePath'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'authorsFileSignatures': value['authorsFileSignatures'] == null ? undefined : ((value['authorsFileSignatures'] as Array<any>).map(FiddSignatureToJSON)),
        'progressiveCrcs': value['progressiveCrcs'] == null ? undefined : ((value['progressiveCrcs'] as Array<any>).map(ProgressiveCrcToJSON)),
        'externalLinks': value['externalLinks'] == null ? undefined : ((value['externalLinks'] as Array<any>).map(ExternalResourceToJSON)),
    };
}

