/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LogicalFileMetadata } from './LogicalFileMetadata';
import {
    LogicalFileMetadataFromJSON,
    LogicalFileMetadataFromJSONTyped,
    LogicalFileMetadataToJSON,
    LogicalFileMetadataToJSONTyped,
} from './LogicalFileMetadata';
import type { FiddKeySection } from './FiddKeySection';
import {
    FiddKeySectionFromJSON,
    FiddKeySectionFromJSONTyped,
    FiddKeySectionToJSON,
    FiddKeySectionToJSONTyped,
} from './FiddKeySection';

/**
 * Describes a logical file within a message
 * @export
 * @interface LogicalFileInfo
 */
export interface LogicalFileInfo {
    /**
     * 
     * @type {LogicalFileMetadata}
     * @memberof LogicalFileInfo
     */
    metadata: LogicalFileMetadata;
    /**
     * 
     * @type {FiddKeySection}
     * @memberof LogicalFileInfo
     */
    section: FiddKeySection;
    /**
     * File offset in the Fidd file
     * @type {number}
     * @memberof LogicalFileInfo
     */
    fileOffset: number;
}

/**
 * Check if a given object implements the LogicalFileInfo interface.
 */
export function instanceOfLogicalFileInfo(value: object): value is LogicalFileInfo {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('section' in value) || value['section'] === undefined) return false;
    if (!('fileOffset' in value) || value['fileOffset'] === undefined) return false;
    return true;
}

export function LogicalFileInfoFromJSON(json: any): LogicalFileInfo {
    return LogicalFileInfoFromJSONTyped(json, false);
}

export function LogicalFileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogicalFileInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': LogicalFileMetadataFromJSON(json['metadata']),
        'section': FiddKeySectionFromJSON(json['section']),
        'fileOffset': json['fileOffset'],
    };
}

export function LogicalFileInfoToJSON(json: any): LogicalFileInfo {
    return LogicalFileInfoToJSONTyped(json, false);
}

export function LogicalFileInfoToJSONTyped(value?: LogicalFileInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': LogicalFileMetadataToJSON(value['metadata']),
        'section': FiddKeySectionToJSON(value['section']),
        'fileOffset': value['fileOffset'],
    };
}

