/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Progressive CRC checksum for streaming verification
 * @export
 * @interface ProgressiveCrc
 */
export interface ProgressiveCrc {
    /**
     * 
     * @type {string}
     * @memberof ProgressiveCrc
     */
    format: string;
    /**
     * Base64-encoded signature/checksum bytes
     * @type {string}
     * @memberof ProgressiveCrc
     */
    bytes: string;
    /**
     * Chunk size for progressive CRC calculation
     * @type {number}
     * @memberof ProgressiveCrc
     */
    progressiveCrcChunkSize: number;
}

/**
 * Check if a given object implements the ProgressiveCrc interface.
 */
export function instanceOfProgressiveCrc(value: object): value is ProgressiveCrc {
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if (!('progressiveCrcChunkSize' in value) || value['progressiveCrcChunkSize'] === undefined) return false;
    return true;
}

export function ProgressiveCrcFromJSON(json: any): ProgressiveCrc {
    return ProgressiveCrcFromJSONTyped(json, false);
}

export function ProgressiveCrcFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgressiveCrc {
    if (json == null) {
        return json;
    }
    return {
        
        'format': json['format'],
        'bytes': json['bytes'],
        'progressiveCrcChunkSize': json['progressiveCrcChunkSize'],
    };
}

export function ProgressiveCrcToJSON(json: any): ProgressiveCrc {
    return ProgressiveCrcToJSONTyped(json, false);
}

export function ProgressiveCrcToJSONTyped(value?: ProgressiveCrc | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': value['format'],
        'bytes': value['bytes'],
        'progressiveCrcChunkSize': value['progressiveCrcChunkSize'],
    };
}

