/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ReadLogicalFileRequest {
    fiddId: string;
    messageNumber: number;
    logicalFilePath: string;
    range?: string;
    list?: ReadLogicalFileListEnum;
    filterIn?: Array<string>;
    filterOut?: Array<string>;
    sort?: ReadLogicalFileSortEnum;
    includeSubfolders?: boolean;
}

/**
 * 
 */
export class DownloadApi extends runtime.BaseAPI {

    /**
     * Creates request options for readLogicalFile without sending the request
     */
    async readLogicalFileRequestOpts(requestParameters: ReadLogicalFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fiddId'] == null) {
            throw new runtime.RequiredError(
                'fiddId',
                'Required parameter "fiddId" was null or undefined when calling readLogicalFile().'
            );
        }

        if (requestParameters['messageNumber'] == null) {
            throw new runtime.RequiredError(
                'messageNumber',
                'Required parameter "messageNumber" was null or undefined when calling readLogicalFile().'
            );
        }

        if (requestParameters['logicalFilePath'] == null) {
            throw new runtime.RequiredError(
                'logicalFilePath',
                'Required parameter "logicalFilePath" was null or undefined when calling readLogicalFile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['list'] != null) {
            queryParameters['list'] = requestParameters['list'];
        }

        if (requestParameters['filterIn'] != null) {
            queryParameters['filterIn'] = requestParameters['filterIn'];
        }

        if (requestParameters['filterOut'] != null) {
            queryParameters['filterOut'] = requestParameters['filterOut'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['includeSubfolders'] != null) {
            queryParameters['includeSubfolders'] = requestParameters['includeSubfolders'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }


        let urlPath = `/{fiddId}/{messageNumber}/{logicalFilePath}`;
        urlPath = urlPath.replace(`{${"fiddId"}}`, encodeURIComponent(String(requestParameters['fiddId'])));
        urlPath = urlPath.replace(`{${"messageNumber"}}`, encodeURIComponent(String(requestParameters['messageNumber'])));
        urlPath = urlPath.replace(`{${"logicalFilePath"}}`, encodeURIComponent(String(requestParameters['logicalFilePath'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Supports HTTP Range requests for partial content retrieval. Use the standard `Range` header (e.g., `Range: bytes=0-1023`) to request specific byte ranges. 
     * Read logical file content (full or partial via Range header)
     */
    async readLogicalFileRaw(requestParameters: ReadLogicalFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.readLogicalFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Supports HTTP Range requests for partial content retrieval. Use the standard `Range` header (e.g., `Range: bytes=0-1023`) to request specific byte ranges. 
     * Read logical file content (full or partial via Range header)
     */
    async readLogicalFile(requestParameters: ReadLogicalFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.readLogicalFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ReadLogicalFileListEnum = {
    M3u: 'm3u'
} as const;
export type ReadLogicalFileListEnum = typeof ReadLogicalFileListEnum[keyof typeof ReadLogicalFileListEnum];
/**
 * @export
 */
export const ReadLogicalFileSortEnum = {
    NumericalAsc: 'NUMERICAL_ASC',
    NumericalDesc: 'NUMERICAL_DESC',
    AlphabeticalAsc: 'ALPHABETICAL_ASC',
    AlphabeticalDesc: 'ALPHABETICAL_DESC'
} as const;
export type ReadLogicalFileSortEnum = typeof ReadLogicalFileSortEnum[keyof typeof ReadLogicalFileSortEnum];
