/* tslint:disable */
/* eslint-disable */
/**
 * Fidd Content API
 * REST wrapper over FiddContentService
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FiddFileMetadata,
  LogicalFileInfo,
} from '../models/index';
import {
    FiddFileMetadataFromJSON,
    FiddFileMetadataToJSON,
    LogicalFileInfoFromJSON,
    LogicalFileInfoToJSON,
} from '../models/index';

export interface GetFiddFileMetadataRequest {
    fiddId: string;
    messageNumber: number;
}

export interface GetLogicalFileInfosRequest {
    fiddId: string;
    messageNumber: number;
}

export interface GetMessageNumbersBeforeRequest {
    fiddId: string;
    messageNumber: number;
    count: number;
    inclusive: boolean;
}

export interface GetMessageNumbersBetweenRequest {
    fiddId: string;
    latestMessage: number;
    inclusiveLatest: boolean;
    earliestMessage: number;
    inclusiveEarliest: boolean;
    count: number;
    getLatest: boolean;
}

export interface GetMessageNumbersTailRequest {
    fiddId: string;
    count: number;
}

/**
 * 
 */
export class MessagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getFiddFileMetadata without sending the request
     */
    async getFiddFileMetadataRequestOpts(requestParameters: GetFiddFileMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fiddId'] == null) {
            throw new runtime.RequiredError(
                'fiddId',
                'Required parameter "fiddId" was null or undefined when calling getFiddFileMetadata().'
            );
        }

        if (requestParameters['messageNumber'] == null) {
            throw new runtime.RequiredError(
                'messageNumber',
                'Required parameter "messageNumber" was null or undefined when calling getFiddFileMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{fiddId}/messages/{messageNumber}/metadata`;
        urlPath = urlPath.replace(`{${"fiddId"}}`, encodeURIComponent(String(requestParameters['fiddId'])));
        urlPath = urlPath.replace(`{${"messageNumber"}}`, encodeURIComponent(String(requestParameters['messageNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Fidd file metadata for a message
     */
    async getFiddFileMetadataRaw(requestParameters: GetFiddFileMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FiddFileMetadata>> {
        const requestOptions = await this.getFiddFileMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FiddFileMetadataFromJSON(jsonValue));
    }

    /**
     * Get Fidd file metadata for a message
     */
    async getFiddFileMetadata(requestParameters: GetFiddFileMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FiddFileMetadata> {
        const response = await this.getFiddFileMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFiddIds without sending the request
     */
    async getFiddIdsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/instances`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all managed Fidd instance IDs
     */
    async getFiddIdsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getFiddIdsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all managed Fidd instance IDs
     */
    async getFiddIds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getFiddIdsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLogicalFileInfos without sending the request
     */
    async getLogicalFileInfosRequestOpts(requestParameters: GetLogicalFileInfosRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fiddId'] == null) {
            throw new runtime.RequiredError(
                'fiddId',
                'Required parameter "fiddId" was null or undefined when calling getLogicalFileInfos().'
            );
        }

        if (requestParameters['messageNumber'] == null) {
            throw new runtime.RequiredError(
                'messageNumber',
                'Required parameter "messageNumber" was null or undefined when calling getLogicalFileInfos().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{fiddId}/messages/{messageNumber}/logical-files`;
        urlPath = urlPath.replace(`{${"fiddId"}}`, encodeURIComponent(String(requestParameters['fiddId'])));
        urlPath = urlPath.replace(`{${"messageNumber"}}`, encodeURIComponent(String(requestParameters['messageNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List logical files for a message
     */
    async getLogicalFileInfosRaw(requestParameters: GetLogicalFileInfosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LogicalFileInfo>>> {
        const requestOptions = await this.getLogicalFileInfosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LogicalFileInfoFromJSON));
    }

    /**
     * List logical files for a message
     */
    async getLogicalFileInfos(requestParameters: GetLogicalFileInfosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LogicalFileInfo>> {
        const response = await this.getLogicalFileInfosRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMessageNumbersBefore without sending the request
     */
    async getMessageNumbersBeforeRequestOpts(requestParameters: GetMessageNumbersBeforeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fiddId'] == null) {
            throw new runtime.RequiredError(
                'fiddId',
                'Required parameter "fiddId" was null or undefined when calling getMessageNumbersBefore().'
            );
        }

        if (requestParameters['messageNumber'] == null) {
            throw new runtime.RequiredError(
                'messageNumber',
                'Required parameter "messageNumber" was null or undefined when calling getMessageNumbersBefore().'
            );
        }

        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling getMessageNumbersBefore().'
            );
        }

        if (requestParameters['inclusive'] == null) {
            throw new runtime.RequiredError(
                'inclusive',
                'Required parameter "inclusive" was null or undefined when calling getMessageNumbersBefore().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        if (requestParameters['inclusive'] != null) {
            queryParameters['inclusive'] = requestParameters['inclusive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{fiddId}/messages/{messageNumber}/before`;
        urlPath = urlPath.replace(`{${"fiddId"}}`, encodeURIComponent(String(requestParameters['fiddId'])));
        urlPath = urlPath.replace(`{${"messageNumber"}}`, encodeURIComponent(String(requestParameters['messageNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get N message numbers before a given message (descending)
     */
    async getMessageNumbersBeforeRaw(requestParameters: GetMessageNumbersBeforeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getMessageNumbersBeforeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get N message numbers before a given message (descending)
     */
    async getMessageNumbersBefore(requestParameters: GetMessageNumbersBeforeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getMessageNumbersBeforeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMessageNumbersBetween without sending the request
     */
    async getMessageNumbersBetweenRequestOpts(requestParameters: GetMessageNumbersBetweenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fiddId'] == null) {
            throw new runtime.RequiredError(
                'fiddId',
                'Required parameter "fiddId" was null or undefined when calling getMessageNumbersBetween().'
            );
        }

        if (requestParameters['latestMessage'] == null) {
            throw new runtime.RequiredError(
                'latestMessage',
                'Required parameter "latestMessage" was null or undefined when calling getMessageNumbersBetween().'
            );
        }

        if (requestParameters['inclusiveLatest'] == null) {
            throw new runtime.RequiredError(
                'inclusiveLatest',
                'Required parameter "inclusiveLatest" was null or undefined when calling getMessageNumbersBetween().'
            );
        }

        if (requestParameters['earliestMessage'] == null) {
            throw new runtime.RequiredError(
                'earliestMessage',
                'Required parameter "earliestMessage" was null or undefined when calling getMessageNumbersBetween().'
            );
        }

        if (requestParameters['inclusiveEarliest'] == null) {
            throw new runtime.RequiredError(
                'inclusiveEarliest',
                'Required parameter "inclusiveEarliest" was null or undefined when calling getMessageNumbersBetween().'
            );
        }

        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling getMessageNumbersBetween().'
            );
        }

        if (requestParameters['getLatest'] == null) {
            throw new runtime.RequiredError(
                'getLatest',
                'Required parameter "getLatest" was null or undefined when calling getMessageNumbersBetween().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latestMessage'] != null) {
            queryParameters['latestMessage'] = requestParameters['latestMessage'];
        }

        if (requestParameters['inclusiveLatest'] != null) {
            queryParameters['inclusiveLatest'] = requestParameters['inclusiveLatest'];
        }

        if (requestParameters['earliestMessage'] != null) {
            queryParameters['earliestMessage'] = requestParameters['earliestMessage'];
        }

        if (requestParameters['inclusiveEarliest'] != null) {
            queryParameters['inclusiveEarliest'] = requestParameters['inclusiveEarliest'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        if (requestParameters['getLatest'] != null) {
            queryParameters['getLatest'] = requestParameters['getLatest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{fiddId}/messages/range`;
        urlPath = urlPath.replace(`{${"fiddId"}}`, encodeURIComponent(String(requestParameters['fiddId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns results in descending order. Use getLatest to select which side to favor when count is smaller than the range.
     * Get N message numbers between two bounds (descending)
     */
    async getMessageNumbersBetweenRaw(requestParameters: GetMessageNumbersBetweenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getMessageNumbersBetweenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns results in descending order. Use getLatest to select which side to favor when count is smaller than the range.
     * Get N message numbers between two bounds (descending)
     */
    async getMessageNumbersBetween(requestParameters: GetMessageNumbersBetweenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getMessageNumbersBetweenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMessageNumbersTail without sending the request
     */
    async getMessageNumbersTailRequestOpts(requestParameters: GetMessageNumbersTailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fiddId'] == null) {
            throw new runtime.RequiredError(
                'fiddId',
                'Required parameter "fiddId" was null or undefined when calling getMessageNumbersTail().'
            );
        }

        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling getMessageNumbersTail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{fiddId}/messages/tail`;
        urlPath = urlPath.replace(`{${"fiddId"}}`, encodeURIComponent(String(requestParameters['fiddId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get latest N message numbers (descending)
     */
    async getMessageNumbersTailRaw(requestParameters: GetMessageNumbersTailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.getMessageNumbersTailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get latest N message numbers (descending)
     */
    async getMessageNumbersTail(requestParameters: GetMessageNumbersTailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getMessageNumbersTailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
